version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      # SSH into the server
      - run:
          name: SSH into the server
          command: ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SERVER_ADDRESS} "cd /consize-backend && git pull && npm i && npm run start:build"
workflows:
  build_and_deploy_work:
    jobs:
      - build_and_deploy
