version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:jc1Yy8ilEa0QQY34o8hQDrO8aPa3YwMJ+IUXWZ6kmyI"
      # SSH into the server
      - run:
          name: SSH into the server
          command: ssh ${SSH_USERNAME}@${SERVER_ADDRESS}

      # Pull the latest changes from Git
      - run:
          name: Pull latest changes from Git
          command: |
            cd /consize-backend
            git checkout main
            git pull

      # Run the build command
      - run:
          name: Run build command
          command: |
            npm install
            npm run start:build
workflows:
  build_and_deploy_work:
    jobs:
      - build_and_deploy
