// Messages
export const SEND_VERIFICATION_EMAIL = "SEND_VERIFICATION_EMAIL"

export const SEND_FORGOT_PASSWORD_EMAIL = "SEND_FORGOT_PASSWORD_EMAIL"

export const SEND_WELCOME_EMAIL = "SEND_WELCOME_EMAIL"
export const SEND_TEAM_INVITATION = "SEND_TEAM_INVITATION"
export const SEND_SIGNATURE_NOTIFICATION_EMAIL = "SEND_SIGNATURE_NOTIFICATION_EMAIL"

export const SEND_WHATSAPP_MESSAGE = "SEND_WHATSAPP_MESSAGE"

// student messages
export const SEND_VERIFICATION_VERIFICATION = "SEND_VERIFICATION_VERIFICATION"
