// Messages
export const SEND_VERIFICATION_EMAIL = "SEND_VERIFICATION_EMAIL"

export const SEND_FORGOT_PASSWORD_EMAIL = "SEND_FORGOT_PASSWORD_EMAIL"

export const SEND_WELCOME_EMAIL = "SEND_WELCOME_EMAIL"
export const SEND_TEAM_INVITATION = "SEND_TEAM_INVITATION"
export const SEND_SIGNATURE_NOTIFICATION_EMAIL = "SEND_SIGNATURE_NOTIFICATION_EMAIL"

export const SEND_WHATSAPP_MESSAGE = "SEND_WHATSAPP_MESSAGE"

export const SEND_LEADERBOARD = "SEND_LEADERBOARD"
export const SEND_CERTIFICATE = "SEND_CERTIFICATE"


export const SEND_LEADERBOARD_SLACK = "SEND_LEADERBOARD_SLACK"
export const SEND_CERTIFICATE_SLACK = "SEND_CERTIFICATE_SLACK"

// student messages
export const SEND_VERIFICATION_VERIFICATION = "SEND_VERIFICATION_VERIFICATION"


// Background events
export const GENERATE_COURSE_TRENDS = "GENERATE_COURSE_TRENDS"


// SCHEDULE
export const RESUME_TOMORROW = "RESUME_TOMORROW"



// Daily routines
export const DAILY_ROUTINE = "DAILY_ROUTINE"
export const DAILY_REMINDER = "DAILY_REMINDER"



// schedule cohorts
export const COHORT_SCHEDULE = "COHORT_SCHEDULE"
export const COHORT_SCHEDULE_STUDENT = "COHORT_SCHEDULE_STUDENT"




// slack messages

export const SEND_SLACK_MESSAGE = "SEND_SLACK_MESSAGE"
export const SEND_SLACK_RESPONSE = "SEND_SLACK_RESPONSE"
export const SEND_SLACK_MODAL = "SEND_SLACK_MODAL"
